version: '2.4'
services:
  Server:
    build: .
    restart: always
    ports:
      - 8089:8089
    depends_on:
      - Mysqldb
  Mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
