version: '2.4'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    network_mode: bridge
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - mysql-data:/var/lib/mysql
      
    ports:
      - "3306:3306"
  app:
    container_name: app
    image: $BUILD_TAG:$BUILD_NUMBER
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://192.168.48.0:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
       SPRING_DATASOURCE_USERNAME: mysql
       SPRING_DATASOURCE_PASSWORD: mysql
    network_mode: bridge
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    
volumes:
    mysql-data:

