version: '2.4'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    network_mode: bridge
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achat
    ports:
      - 3306:3306
      
    volumes:
      - db:/var/lib/mysql
  app:
    image: $BUILD_TAG:$BUILD_NUMBER
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : root,
        "spring.datasource.password" : root,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        network_mode: bridge
      }'
      
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
