version: '2.4'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    network_mode: bridge
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=tpachato
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=
    volumes:
      - mysql-data:/var/lib/mysql
      
    ports:
      - "3306:3306"
  app:
    container_name: app
    image: $BUILD_TAG:$BUILD_NUMBER
    network_mode: bridge
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    
volumes:
    mysql-data:
networks:
  kell-network:
    driver: bridge
