version: '2.4'
services:
  app:
    image: 142033/spring:$BUILD_NUMBER
    ports:
      - "8089:8089"
    depends_on:
      - mysql
  mysql:
    image: docker.io/mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_DATABASE= tpachat
      - MYSQL_USER= root
      - MYSQL_PASSWORD= root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
    mysql-data:

